name: "Build, test, and lint"
description: "pnpm run build, test, and lint scripts"
inputs:
  PACKAGE_MANAGER:
    description: "package manager to use. (default: 'auto')"
    required: false
  SCRIPTS:
    description: "package.json scripts to run. (default: 'build,lint,test,docs')"
    required: false
  NO_BAIL:
    description: "Don't bail on script failures [true/false] (default: false)"
    required: false
  BAIL_ON_MISSING:
    description: "Bail on missing script [true/false] (default: false)"
    required: false
  AUTOFIX_LOCKFILE:
    description: "Autofix and commit lockfile when mismatched. [true/false] (default: true)"
    required: false
  AUTOFIX_LINT:
    description: "Autofix and commit lint errors. [false/string script name for fix] (default: 'lint:fix')"
    required: false
  BAIL_ON_DIRTY:
    description: "Fail if there are untracked changes. [true/false/string error message] (default: false)"
    required: false
  AUTO_COMMIT:
    description: "Paths that are allowed to be automatically committed if changed. [true/false] (default: false)"
    required: false
  GITHUB_TOKEN:
    description: GitHub token to use.
    required: false
  NPM_REGISTRY:
    description: "NPM registry to use. (default: 'https://registry.npmjs.org')"
    required: false
  NPM_REGISTRY_SCOPE:
    description: "NPM registry scope to use. (default: '')"
    required: false
  NPM_TOKEN:
    description: NPM token to use.
    required: false
  NODE_VERSION:
    description: "Node version to use. (default: 'lts/*')"
    required: false
    default: "lts/*"
  PREVENT_COMMITS:
    description: "Prevent commits. [true/false] (default: false)"
    required: false
  DEBUG:
    description: "Manually debug the action. [true/false] (default: false)"
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ inputs.GITHUB_TOKEN || env.GITHUB_TOKEN || github.token }}

    - uses: actions/checkout@v3
      if: github.event_name == 'merge_group'
      with:
        fetch-depth: 0
        ref: ${{ github.event.merge_group.head.ref }}
        token: ${{ inputs.GITHUB_TOKEN || env.GITHUB_TOKEN || github.token }}

    - uses: actions/checkout@v3
      if: github.event_name == 'push'
      with:
        fetch-depth: 0
        token: ${{ inputs.GITHUB_TOKEN || env.GITHUB_TOKEN || github.token }}

    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
      env:
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION || 'lts/*' }}
        cache: ${{ inputs.PACKAGE_MANAGER }}
        registry-url: ${{ inputs.NPM_REGISTRY || 'https://registry.npmjs.org' }}
        scope: ${{ inputs.NPM_REGISTRY_SCOPE || '' }}
      env:
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}

    - name: Run build checks
      run: node ${{ github.action_path }}/dist/index.js '${{ toJSON(inputs) }}'
      shell: bash
      env:
        FORCE_COLOR: "3"
